# https://github.com/sphinx-notes/pages/tree/v3

name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main, feature_gh-pages]

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: sphinx-notes/pages@v3
